name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Set version
        id: version
        run: echo "name=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: Build and archive binary
        run: |
          go build -o recall2cache
          tar -czvf recall2cache.tar.gz recall2cache

      - name: Create GitHub Release
        run: |
          gh release create ${{ steps.version.outputs.name }} \
            --title "${{ steps.version.outputs.name }}" \
            --notes "Automated release for version ${{ steps.version.outputs.name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_RECALL2CACHE }}

      - name: Upload Release Asset
        run: |
          gh release upload ${{ steps.version.outputs.name }} recall2cache.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_RECALL2CACHE }}
