name: Build and Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Custom release version (optional)'
        required: false

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: linux
            goos: linux
            goarch: amd64
            filename: recall2cache
            archive_cmd: tar -czvf
            archive_ext: .tar.gz
          - os: darwin
            goos: darwin
            goarch: amd64
            filename: recall2cache-darwin
            archive_cmd: tar -czvf
            archive_ext: .tar.gz
          - os: windows
            goos: windows
            goarch: amd64
            filename: recall2cache.exe
            archive_cmd: zip -r
            archive_ext: .zip

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -o ${{ matrix.filename }}

      - name: Create archive
        run: |
          ${{ matrix.archive_cmd }} ${{ matrix.filename }}${{ matrix.archive_ext }} ${{ matrix.filename }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.filename }}-artifact
          path: ${{ matrix.filename }}${{ matrix.archive_ext }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: '*-artifact'

      - name: List artifacts
        run: ls -R artifacts

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(date +'%Y.%m.%d')
          gh release create $VERSION \
            --title "$VERSION" \
            artifacts/*.{tar.gz,zip}