name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24'

      - name: Build binary
        run: go build -o recall2cache

      - name: Archive binary
        run: tar -czvf recall2cache.tar.gz recall2cache

      - name: Get current date
        id: date
        run: echo "name=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        run: |
          gh release create ${{ steps.date.outputs.date }} recall2cache.tar.gz \
            --title "Release ${{ steps.date.outputs.date }}" \
            --notes "Automated release for version ${{ steps.date.outputs.date }}"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_RECALL2CACHE }}

      - name: Upload Release Asset
        run: |
          gh release upload ${{ steps.date.outputs.name }} recall2cache.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_RECALL2CACHE }}
