name: Build and Release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install GoReleaser
        run: |
          curl -sL https://git.io/goreleaser | bash

      - name: Set version
        id: version
        run: echo "name=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: Build and release
        run: goreleaser release --rm-dist --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_RECALL2CACHE }}
